//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_tablelist
    {
        public int IDAsisTableList { get; set; }
        public Nullable<int> IDAsisModule { get; set; }
        public string TableName { get; set; }
        public string SortID { get; set; }
        public Nullable<bool> HasHistory { get; set; }
        public Nullable<bool> IsMultiLingual { get; set; }
        public string DescriptionNL { get; set; }
        public string DescriptionEN { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
